import Link from "next/link";
import Head from "next/head";
import styles from "./Layout.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <nav className={styles.navContainer}>
        <ul className={styles.navList}>
          <li className={styles.navItem}>
            <Link href="/" passHref>
              <a className={styles.linkContainer}>Home</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/all-projects" passHref>
              <a className={styles.linkContainer}>Projects</a>
            </Link>
          </li>
          <li className={styles.navItem}>
            <Link href="/contact-me" passHref>
              <a className={styles.linkContainer}>Contact Me</a>
            </Link>
          </li>
        </ul>
      </nav>
      {children}
    </>
  );
}
